# Generated by Django 4.0.3 on 2022-04-07 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0002_bookmark"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comments", models.ManyToManyField(to="testapp.comment")),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="testapp.site"
                    ),
                ),
            ],
        ),
    ]
