# Generated by Django 3.2.20 on 2023-07-13 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_commentgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.IntegerField(default=0)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.bookmark')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, null=True, to='testapp.comment')),
            ],
        ),
    ]
