name: Code Style

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10
      - name: Install Dependencies
        run: python -m pip install -Ur requirements_dev.txt
      - name: Run flake8
        run: flake8 django_scopes tests
  isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10
      - name: Install Dependencies
        run: python -m pip install -Ur requirements_dev.txt
      - name: Run isort
        run: isort --check -rc django_scopes tests
